const LOCAL_IMAGE_API_ROUTE = '/img';
const LOCAL_BUNDLE_API_ROUTE = '/bundle_document';

const LOCAL_API_ROUTES = {
  LOCAL_IMAGE_API_ROUTE,
  LOCAL_BUNDLE_API_ROUTE,
};

export {
  LOCAL_API_ROUTES as default,
  LOCAL_IMAGE_API_ROUTE,
  LOCAL_BUNDLE_API_ROUTE,
};
